export const questions: string[] = [
  // Big Five Personality Traits's questions
  "You are the life of the party.",
  "You feel little concern for others.",
  "You are always prepared.",
  "You get stressed out easily.",
  "You have a rich vocabulary.",
  "You don't talk a lot.",
  "You are interested in people.",
  "You leave your belongings around.",
  "You are relaxed most of the time.",
  "You have difficulty understanding abstract ideas.",
  "You feel comfortable around people.",
  "You insult people.",
  "You pay attention to details.",
  "You worry about things.",
  "You have a vivid imagination.",
  "You keep in the background.",
  "You sympathize with others' feelings.",
  "You make a mess of things.",
  "You seldom feel blue.",
  "You are not interested in abstract ideas.",
  "You start conversations.",
  "You are not interested in other people's problems.",
  "You get chores done right away.",
  "You are easily disturbed.",
  "You have excellent ideas.",
  "You have little to say.",
  "You have a soft heart.",
  "You often forget to put things back in their proper place.",
  "You get upset easily.",
  "You do not have a good imagination.",
  "You talk to a lot of different people at parties.",
  "You are not really interested in others.",
  "You like order.",
  "You change your mood a lot.",
  "You are quick to understand things.",
  "You don't like to draw attention to yourself.",
  "You take time out for others.",
  "You shirk your duties.",
  "You have frequent mood swings.",
  "You use difficult words.",
  "You don't mind being the center of attention.",
  "You feel others' emotions.",
  "You follow a schedule.",
  "You get irritated easily.",
  "You spend time reflecting on things.",
  "You are quiet around strangers.",
  "You make people feel at ease.",
  "You are exacting in your work.",
  "You often feel blue.",
  "You are full of ideas.",

  // Schwartz Theory of Basic Human Values's questions
  "Thinking up new ideas and being creative is important to him. He likes to do things in his own original way.",
  "It is important to him to be rich. He wants to have a lot of money and expensive things.",
  "He thinks it is important that every person in the world should be treated equally. He believes everyone should have equal opportunities in life.",
  "It's important to him to show his abilities. He wants people to admire what he does.",
  "It is important to him to live in secure surroundings. He avoids anything that might endanger his safety.",
  "He likes surprises and is always looking for new things to do. He thinks it is important to do lots of different things in life.",
  "He believes that people should do what they're told. He thinks people should follow rules at all times, even when no one is watching.",
  "It is important to him to listen to people who are different from him. Even when he disagrees with them, he still wants to understand them.",
  "It is important to him to be humble and modest. He tries not to draw attention to himself.",
  "Having a good time is important to him. He likes to “spoil” himself.",
  "It is important to him to make his own decisions about what he does. He likes to be free and not depend on others.",
  "It's very important to him to help the people around him. He wants to care for their well-being.",
  "Being very successful is important to him. He hopes people will recognize his achievements.",
  "It is important to him that the government ensures his safety against all threats. He wants the state to be strong so it can defend its citizens.",
  "He looks for adventures and likes to take risks. He wants to have an exciting life.",
  "It is important to him always to behave properly. He wants to avoid doing anything people would say is wrong.",
  "It is important to him to get respect from others. He wants people to do what he says.",
  "It is important to him to be loyal to his friends. He wants to devote himself to people close to him.",
  "He strongly believes that people should care for nature. Looking after the environment is important to him.",
  "Tradition is important to him. He tries to follow the customs handed down by his religion or his family.",
  "He seeks every chance he can to have fun. It is important to him to do things that give him pleasure.",
];
