import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomNavbar } from "@/components/elements/Navbar";
import { QuizProvider } from "@/components/contexts/QuizContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QuizProvider>
      <html lang="en">
        <body>
          <CustomNavbar />
          {children}
        </body>
      </html>
    </QuizProvider>
  );
}
